export const FIGURE_WIDTH = 150
export const FIGURE_HEIGHT = 40

export const FIGURE_PLUS_WIDTH = 30

export const HEIGHT_SPACE = 20

export const FIGURE_HALF_WIDTH = FIGURE_WIDTH / 2
export const FIGURE_HALF_HEIGHT = FIGURE_HEIGHT / 2
export const FIGURE_PLUS_HALF_WIDTH = FIGURE_PLUS_WIDTH / 2

export const FIGURE_ARC_LENGTH = 10
export const FIGURE_PLUS_ARC_LENGTH = 3
export const FIGURE_WIDTH_WO_ARC_LENGTH = FIGURE_WIDTH - FIGURE_ARC_LENGTH
export const FIGURE_HEIGHT_WO_ARC_LENGTH = FIGURE_HEIGHT - FIGURE_ARC_LENGTH
export const FIGURE_PLUS_WIDTH_WO_ARC_LENGTH = FIGURE_PLUS_WIDTH - FIGURE_PLUS_ARC_LENGTH
